src/Entity/Autorisation/AgreementExportateur.php
<?php

namespace App\Entity\Autorisation;

use App\Entity\References\Exportateur;
use App\Repository\Autorisation\AgreementExportateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Table(name: 'metier.agreement_exportateur')]
#[ORM\Entity(repositoryClass: AgreementExportateurRepository::class)]
class AgreementExportateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $numero_decision = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_decision = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(length: 255)]
    private ?string $created_by = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $updated_by = null;

    #[ORM\OneToMany(mappedBy: 'code_agreement', targetEntity: AutorisationExportateur::class)]
    private Collection $autorisationExportateurs;

    #[ORM\Column(nullable: true)]
    private ?bool $statut = null;

    #[ORM\Column(nullable: true)]
    private ?bool $reprise = null;

    #[ORM\ManyToOne(inversedBy: 'agreementExportateurs')]
    private ?Exportateur $code_exportateur = null;

    public function __construct()
    {
        $this->autorisationExportateurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroDecision(): ?string
    {
        return $this->numero_decision;
    }

    public function setNumeroDecision(string $numero_decision): static
    {
        $this->numero_decision = $numero_decision;

        return $this;
    }

    public function getDateDecision(): ?\DateTimeInterface
    {
        return $this->date_decision;
    }

    public function setDateDecision(?\DateTimeInterface $date_decision): static
    {
        $this->date_decision = $date_decision;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(string $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUpdatedBy(): ?string
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?string $updated_by): static
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * @return Collection<int, AutorisationExportateur>
     */
    public function getAutorisationExportateurs(): Collection
    {
        return $this->autorisationExportateurs;
    }

    public function addAutorisationExportateur(AutorisationExportateur $autorisationExportateur): static
    {
        if (!$this->autorisationExportateurs->contains($autorisationExportateur)) {
            $this->autorisationExportateurs->add($autorisationExportateur);
            $autorisationExportateur->setCodeAgreement($this);
        }

        return $this;
    }

    public function removeAutorisationExportateur(AutorisationExportateur $autorisationExportateur): static
    {
        if ($this->autorisationExportateurs->removeElement($autorisationExportateur)) {
            // set the owning side to null (unless already changed)
            if ($autorisationExportateur->getCodeAgreement() === $this) {
                $autorisationExportateur->setCodeAgreement(null);
            }
        }

        return $this;
    }

    public function isStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(?bool $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function isReprise(): ?bool
    {
        return $this->reprise;
    }

    public function setReprise(?bool $reprise): static
    {
        $this->reprise = $reprise;

        return $this;
    }

    public function getCodeExportateur(): ?Exportateur
    {
        return $this->code_exportateur;
    }

    public function setCodeExportateur(?Exportateur $code_exportateur): static
    {
        $this->code_exportateur = $code_exportateur;

        return $this;
    }

    public function __toString(): string
    {
        return $this->numero_decision." ". $this->getCodeExportateur()->getRaisonSocialeExportateur();
    }
}

src/Form/Autorisation/AgreementExportateurType.php
<?php

namespace App\Form\Autorisation;

use App\Entity\Autorisation\AgreementExportateur;
use App\Entity\References\Exportateur;
use App\Repository\References\ExportateurRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Contracts\Translation\TranslatorInterface;

class AgreementExportateurType extends AbstractType
{
    public function __construct(private TranslatorInterface $translator)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('numero_decision', TextType::class, [
                'label'=>$this->translator->trans('Decision No'),
                'required'=>true,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'attr'=>[
                    'class'=>'form-control sigle numero_decision',
                    'style'=>'background-color:lightpink; font-size:20px; font-weight:bold;'

                ],
                'constraints' => [
                    new NotBlank([
                        'message' => $this->translator->trans('Decision No is mandatory')
                    ])
                ]
            ])
            ->add('date_decision', DateType::class, [
                'label'=>$this->translator->trans('Decision Date'),
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'dd/MM/yyyy',
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'attr'=>[
                    'class'=>'form-control date_decision',
                    'style'=>'background-color:lightyellow'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => $this->translator->trans('Decision Date is mandatory')
                    ])
                ]

            ])

            ->add('code_exportateur', EntityType::class, [
                'label'=>$this->translator->trans('Exporter'),
                'class'=>Exportateur::class,
                'required'=>true,
                'multiple'=>false,
                'expanded'=>false,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'query_builder' => function (ExportateurRepository $att): QueryBuilder {
                    return $att->createQueryBuilder('e')
//                        ->andWhere('e.email_personne_ressource is not null')
//                        ->andWhere('e.statut = false or e.statut is NULL')
                        ->orderBy('e.raison_sociale_exportateur', 'ASC');
                },
                'attr'=>[
                    'class'=>'form-control code_exportateur alert-primary font-weight-bold'
                ]

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => AgreementExportateur::class
        ]);
    }
}

src/Form/Autorisation/AgreementPsType.php
<?php

namespace App\Form\Autorisation;

use App\Entity\Autorisation\AgreementPs;
use App\Entity\Autorisation\Attribution;
use App\Entity\References\AttributairePs;
use App\Entity\References\Exploitant;
use App\Entity\References\Foret;
use App\Entity\References\TypeDossierPs;
use App\Repository\References\AttributairePsRepository;
use App\Repository\References\ExploitantRepository;
use App\Repository\References\ForetRepository;
use App\Repository\References\TypeDossierPsRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Contracts\Translation\TranslatorInterface;

class AgreementPsType extends  AbstractType
{
    public function __construct(private TranslatorInterface $translator)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('numero_dossier', TextType::class, [
                'label'=>$this->translator->trans('Folder No'),
                'required'=>true,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'attr'=>[
                    'class'=>'form-control sigle numero_dossier',
                    'style'=>'background-color:lightpink; font-size:20px; font-weight:bold;',
                    'readonly'=>true
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => $this->translator->trans('Folder No is mandatory')
                    ])
                ]
            ])
            ->add('dateOuverture', DateType::class, [
                'label'=>$this->translator->trans('Open Date'),
                'widget'=>'single_text',
                'required'=>true,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'attr'=>[
                    'class'=>'form-control sigle',
                    'style'=>'background-color:lightyellow'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => $this->translator->trans('Open Date is mandatory')
                    ])
                ]

            ])
            ->add('montant_agrement', NumberType::class, [
                'label'=>$this->translator->trans('Agreement amount'),
                'required'=>true,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'attr'=>[
                    'class'=>'form-control montant ',
                    'style'=>'background-color:lightyellow; font-size:32px; font-weight:bold;',
                    'readonly'=>true
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => $this->translator->trans('Agreement amount is mandatory')
                    ])
                ]

            ])
            ->add('code_attributaire_ps', EntityType::class, [
                'label'=>$this->translator->trans('Owner'),
                'class'=>AttributairePs::class,
                'required'=>true,
                'multiple'=>false,
                'expanded'=>false,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'query_builder' => function (AttributairePsRepository $att): QueryBuilder {
                    return $att->createQueryBuilder('a')
                        ->andWhere('a.statut = true')
                        ->orderBy('a.raison_sociale', 'ASC');
                },
                'attr'=>[
                    'class'=>'form-control code_attributaire_ps alert-primary font-weight-bold'
                ]

            ])

            ->add('code_type_dossier', EntityType::class, [
                'label'=>$this->translator->trans('Activity Type'),
                'class'=>TypeDossierPs::class,
                'required'=>true,
                'multiple'=>false,
                'expanded'=>false,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'query_builder' => function (TypeDossierPsRepository $type_dossier): QueryBuilder {
                    return $type_dossier->createQueryBuilder('t')
                        ->andWhere('t.montant_agreement is not null')
                        ->orderBy('t.libelle', 'ASC');
                },
                'attr'=>[
                    '           class'=>'form-control text-sm text-sm text-dark type_dossier alert-primary font-weight-bold'
                ]

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => AgreementPs::class
        ]);
    }
}

src/Form/Autorisation/AttributionType.php
<?php

namespace App\Form\Autorisation;

use App\Entity\Autorisation\Attribution;
use App\Entity\References\Exploitant;
use App\Entity\References\Foret;
use App\Repository\References\ExploitantRepository;
use App\Repository\References\ForetRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Contracts\Translation\TranslatorInterface;

class AttributionType extends AbstractType
{
    public function __construct(private TranslatorInterface $translator)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('numero_decision', IntegerType::class, [
                'label'=>'N° Décision',
                'required'=>true,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'attr'=>[
                    'class'=>'form-control sigle',
                    'style'=>'background-color:lightyellow'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => $this->translator->trans('Decision number is mandatory')
                    ])
                ]
            ])
            ->add('date_decision', DateType::class, [
                'label'=>'Date Décision',
                'widget'=>'single_text',
                'required'=>true,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'attr'=>[
                    'class'=>'form-control sigle',
                    'style'=>'background-color:lightyellow'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => $this->translator->trans('Decision date is mandatory')
                    ])
                ]

            ])

            ->add('code_foret', EntityType::class, [
                'label'=>'Forêt',
                'class'=>Foret::class,
                'required'=>true,
                'multiple'=>false,
                'expanded'=>false,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'attr'=>[
                    '           class'=>'form-control code_foret'
                ],
                'query_builder' => function (ForetRepository $foret): QueryBuilder {
                    return $foret->createQueryBuilder('f')
                        ->andWhere('f.attribue =false')
                        ->andWhere('f.code_cantonnement is not null')
                        ->andWhere('f.code_type_foret = 1');
                }

            ])

            ->add('code_exploitant', EntityType::class, [
                'label'=>'Exploitant forestier',
                'class'=>Exploitant::class,
                'required'=>true,
                'multiple'=>false,
                'expanded'=>false,
                'label_attr'=>[
                    'class'=>'fw-bold text-dark'
                ],
                'query_builder' => function (ExploitantRepository $exploitant): QueryBuilder {
                    return $exploitant->createQueryBuilder('e')
                        ->andWhere('e.email_personne_ressource is not null')
                        ->orderBy('e.raison_sociale_exploitant', 'ASC');
                },
                'attr'=>[
                    '           class'=>'form-control text-sm text-sm alert-light text-dark code_exploitant'
                ]

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Attribution::class,
        ]);
    }
}

templates/autorisation/agreement_exportateur/add-agreement-exportateur.html.twig
{% extends 'template_base.html.twig' %}

{% block Title %}
    {% trans %}SNVLT{% endtrans%} - {% trans %}Export/Import approval{% endtrans %}
{% endblock %}


{% block titre_page %}
    <h2 class="text-dark font-weight-bold mb-2">
        <img src="{{ asset('assets/images/webapp/exports_aproval.png') }}" alt="attribution">  {% trans %}Export/Import approval{% endtrans %} - {% trans %}[ADD]{% endtrans %}
    </h2>
{% endblock %}


 {% block notifs %}
     {% include 'base/notifs.html.twig' %}
 {% endblock %}

 {% block menu %}
     {% include 'base/menu.html.twig' %}
 {% endblock %}

{% block page_content %}
    {% set options = option_service.findAll %}
    <link href="{{ asset('assets/dselect-main/dist/css/dselect.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="{{ asset('assets/css/style_snvlt.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/Js/date-picher/css/date-picker.min.css') }}">

    <section class="section">
        <div class="p-2 w-100 banniere"></div>
        <div class="card">
            <div class="card-body">
                {{ form_start(form, {'attr': {novalidate: 'novalidate'}}) }}
                <div class="row p-3 bg-white m-1">
                    <div class="col-md-4">

                        <div class="">{{ form_row(form.numero_decision) }}</div>
                        <div class="input-group">
                            {{ form_row(form.date_decision)}}
                            <button class="btn btn-outline-secondary" type="button" id="date-toggle" style="background-color: white; border: 0px;"><i class="mdi mdi-calendar text-dark font-weight-bold" style="font-size: 32px;"></i></button>
                            <div id="date-export"></div>
                        </div>
                        <div class="">{{ form_row(form.code_exportateur) }}</div>

                        {% set valeur = options['autorisations_validation'] %}

                        <hr>
                        <a href="{{ path('ref_directions') }}" class="btn btn-sm bg-danger p-2 me-2 ms-5 text-white" style="font-weight: lighter"><i class="mdi mdi-backspace" style="font-size: 18px;margin-right: 10px;"></i>{% trans %}Back to list{% endtrans %}</a>
                        <button type="submit"  class="btn btn-sm bg-primary text-white p-2" style="margin-left: 10px;font-weight: lighter">
                            <i class="mdi mdi-database-edit" style="font-size: 18px;margin-right: 10px"></i>{% trans %}Add Agreement{% endtrans %}
                        </button>
                    </div>
                </div>

                {{ form_end(form) }}
            </div>
        </div>



        <!--Modification de l'attribution -->

    </section>

    <script src="{{ asset('assets/Js/date-picher/js/date-picker.min.js') }}"></script>
    <script src="{{ asset('assets/dselect-main/dist/js/dselect.min.js') }}"></script>
    <script src="{{ asset('assets/assets/js/jquery.min-3.5.1.js') }}"></script>
    <script src="{{ asset('assets/select2/select2.min.js') }}"></script>
    <script>
        const dateDemo = new DatePicker({
            el: '#date-export',
            toggleEl: '#date-toggle',
            inputEl: '#agreement_exportateur_date_decision',
            inputToggle: true,
        });

    </script>

    <script>
            $('#btn-date').on('click', function (e){
                let test = $('#agreement_exportateur_date_decision').val();

                $("#agreement_exportateur_date_decision").val($.datepicker.formatDate('dd M yy', test));
            })
    </script>


{% endblock %}

templates/autorisation/agreement_exportateur/index.html.twig
{% extends 'template_base.html.twig' %}

{% block Title %}
    {% trans %}SNVLT{% endtrans%} - {% trans %}Export/Import approval{% endtrans %}
{% endblock %}

{% block titre_page %}
    <h2 class="text-dark font-weight-bold mb-2">
        <img src="{{ asset('assets/images/webapp/exports_aproval.png') }}" alt="attribution">  {% trans %}Export/Import approval{% endtrans %}
    </h2>
    <div class="d-sm-flex justify-content-xl-between align-items-center mb-2">
        <div class="btn-group p-1 rounded-5 " role="group" aria-label="Basic example">
            <a class="btn btn-inverse-danger p-2 mt-2" style="border: 0px; font-size: 16px;" href="{{ path('agreementexpimp.edit') }}"> <i class="mdi mdi-plus-circle me-2" style="font-size: 20px;"></i>{% trans %}Add{% endtrans %}</a>
        </div>
    </div>
{% endblock %}

 {% block menu %}
     {% include 'base/menu.html.twig' %}
 {% endblock %}
{% block notifs %}
     {% include 'base/notifs.html.twig' %}
 {% endblock %}

{% block page_content %}
    <link rel="stylesheet" href="{{ asset('assets/webapp/assets/vendors/simple-datatables/style.css') }}">
    <section class="section">
        <table class="table table-responsive-sm bg-white" id="agreementexport">
            <thead>
            <tr style="background: #0e5e73; color: #f0fcf0;">
                <th style="font-size: 18px;">{% trans %}Decision No{% endtrans %}</th>
                <th class="text-center" style="font-size: 18px;">{% trans %}Decision Date{% endtrans %}</th>
                <th style="font-size: 18px;">{% trans %}Exporter{% endtrans %}</th>
                <th style="font-size: 18px;">{% trans %}Cantonment{% endtrans %}</th>
                <th style="font-size: 18px;">{% trans %}Actions{% endtrans %}</th>
            </tr>
            </thead>
            <tbody>
            {% for agreement in agreementexports %}
                {% if(agreement.statut) %}
                    <tr class="alert-success">
                {% else %}
                    <tr class="alert-danger">
                {% endif %}
                <td class="text-dark font-weight-bold"><a class="text-dark editBtn" style="font-size: 16px; font-weight: bold;" href="{{ path('agreementexpimp.edit', {'id_exportateur': agreement.id}) }}" id="{{ agreement.id }}">{{ agreement.numeroDecision }}</a></td>
                <td class="text-dark font-weight-bold text-center">{{ agreement.dateDecision | date('d/m/Y') }}</td>
                <td class="text-dark  "><span class="badge p-1 bg-dark text-white" style="font-size: 16px;border-radius: 10px;">{{ agreement.codeExportateur.raisonSocialeExportateur }} - [{{ agreement.codeExportateur.codeExportateur }}]</span></td>
                <td class="text-dark font-weight-bold">{{ agreement.codeExportateur.codeCantonnement.nomCantonnement }}</a></td>
                <td class="text-dark font-weight-bold "><a class="btn btn-sm text-danger"><i class="mdi mdi-cancel" style="font-size:  24px;" title="Retirer / Abandonner..."></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>

    <script src="{{ asset('assets/webapp/assets/vendors/simple-datatables/simple-datatables.js') }}"></script>
    <script src="{{ asset('assets/webapp/assets/vendors/jquery/jquery.min.js') }}"></script>

    <script>
        // Simple Datatable
        let table1 = document.querySelector('#agreementexport');
        let dataTable = new simpleDatatables.DataTable(table1);
    </script>

{% endblock %}