src/Entity/Transformation/Billon.php
<?php

namespace App\Entity\Transformation;

use App\Entity\DocStats\Saisie\Lignepagelje;
use App\Entity\References\TypeTransformation;
use App\Repository\Transformation\BillonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Table(name: 'transformation.billon')]
#[ORM\Entity(repositoryClass: BillonRepository::class)]
class Billon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $numero_billon = null;

    #[ORM\Column]
    private ?int $lng = null;

    #[ORM\Column]
    private ?int $dm = null;

    #[ORM\Column]
    private ?float $volume = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_billonnage = null;

    #[ORM\Column(nullable: true)]
    private ?int $nb_elements = null;

    #[ORM\ManyToOne(inversedBy: 'billons')]
    private ?Lignepagelje $code_lignepagelje = null;

    #[ORM\ManyToOne(inversedBy: 'billons')]
    private ?TypeTransformation $type_transformation = null;

    #[ORM\OneToMany(mappedBy: 'code_billon', targetEntity: Elements::class)]
    private Collection $elements;

    #[ORM\Column(nullable: true)]
    private ?bool $cloture = null;

    #[ORM\Column(nullable: true)]
    private ?bool $rebus = null;

    #[ORM\ManyToOne(inversedBy: 'billons')]
    private ?FicheLot $code_lot = null;

    public function __construct()
    {
        $this->elements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroBillon(): ?string
    {
        return $this->numero_billon;
    }

    public function setNumeroBillon(string $numero_billon): static
    {
        $this->numero_billon = $numero_billon;

        return $this;
    }

    public function getLng(): ?int
    {
        return $this->lng;
    }

    public function setLng(int $lng): static
    {
        $this->lng = $lng;

        return $this;
    }

    public function getDm(): ?int
    {
        return $this->dm;
    }

    public function setDm(int $dm): static
    {
        $this->dm = $dm;

        return $this;
    }

    public function getVolume(): ?float
    {
        return $this->volume;
    }

    public function setVolume(float $volume): static
    {
        $this->volume = $volume;

        return $this;
    }

    public function getDateBillonnage(): ?\DateTimeInterface
    {
        return $this->date_billonnage;
    }

    public function setDateBillonnage(\DateTimeInterface $date_billonnage): static
    {
        $this->date_billonnage = $date_billonnage;

        return $this;
    }

    public function getNbElements(): ?int
    {
        return $this->nb_elements;
    }

    public function setNbElements(?int $nb_elements): static
    {
        $this->nb_elements = $nb_elements;

        return $this;
    }

    public function getCodeLignepagelje(): ?Lignepagelje
    {
        return $this->code_lignepagelje;
    }

    public function setCodeLignepagelje(?Lignepagelje $code_lignepagelje): static
    {
        $this->code_lignepagelje = $code_lignepagelje;

        return $this;
    }

    public function getTypeTransformation(): ?TypeTransformation
    {
        return $this->type_transformation;
    }

    public function setTypeTransformation(?TypeTransformation $type_transformation): static
    {
        $this->type_transformation = $type_transformation;

        return $this;
    }

    /**
     * @return Collection<int, Elements>
     */
    public function getElements(): Collection
    {
        return $this->elements;
    }

    public function addElement(Elements $element): static
    {
        if (!$this->elements->contains($element)) {
            $this->elements->add($element);
            $element->setCodeBillon($this);
        }

        return $this;
    }

    public function removeElement(Elements $element): static
    {
        if ($this->elements->removeElement($element)) {
            // set the owning side to null (unless already changed)
            if ($element->getCodeBillon() === $this) {
                $element->setCodeBillon(null);
            }
        }

        return $this;
    }

    public function isCloture(): ?bool
    {
        return $this->cloture;
    }

    public function setCloture(?bool $cloture): static
    {
        $this->cloture = $cloture;

        return $this;
    }

    public function isRebus(): ?bool
    {
        return $this->rebus;
    }

    public function setRebus(?bool $rebus): static
    {
        $this->rebus = $rebus;

        return $this;
    }

    public function getCodeLot(): ?FicheLot
    {
        return $this->code_lot;
    }

    public function setCodeLot(?FicheLot $code_lot): static
    {
        $this->code_lot = $code_lot;

        return $this;
    }
}

src/Entity/Transformation/FicheJourTransfo.php
<?php

namespace App\Entity\Transformation;

use App\Entity\References\Essence;
use App\Entity\References\TypeTransformation;
use App\Repository\Transformation\FicheJourTransfoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Table(name: 'transformation.fiche_jour_transfo')]
#[ORM\Entity(repositoryClass: FicheJourTransfoRepository::class)]
class FicheJourTransfo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fiche = null;

    #[ORM\ManyToOne(inversedBy: 'ficheJourTransfos')]
    private ?TypeTransformation $TypeTransformation = null;

    #[ORM\ManyToOne(inversedBy: 'ficheJourTransfos')]
    private ?Essence $essence = null;

    #[ORM\OneToMany(mappedBy: 'code_fiche', targetEntity: DetailFicheJourTransfo::class)]
    private Collection $detailFicheJourTransfos;

    public function __construct()
    {
        $this->detailFicheJourTransfos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateFiche(): ?\DateTimeInterface
    {
        return $this->date_fiche;
    }

    public function setDateFiche(\DateTimeInterface $date_fiche): static
    {
        $this->date_fiche = $date_fiche;

        return $this;
    }

    public function getTypeTransformation(): ?TypeTransformation
    {
        return $this->TypeTransformation;
    }

    public function setTypeTransformation(?TypeTransformation $TypeTransformation): static
    {
        $this->TypeTransformation = $TypeTransformation;

        return $this;
    }

    public function getEssence(): ?Essence
    {
        return $this->essence;
    }

    public function setEssence(?Essence $essence): static
    {
        $this->essence = $essence;

        return $this;
    }

    /**
     * @return Collection<int, DetailFicheJourTransfo>
     */
    public function getDetailFicheJourTransfos(): Collection
    {
        return $this->detailFicheJourTransfos;
    }

    public function addDetailFicheJourTransfo(DetailFicheJourTransfo $detailFicheJourTransfo): static
    {
        if (!$this->detailFicheJourTransfos->contains($detailFicheJourTransfo)) {
            $this->detailFicheJourTransfos->add($detailFicheJourTransfo);
            $detailFicheJourTransfo->setCodeFiche($this);
        }

        return $this;
    }

    public function removeDetailFicheJourTransfo(DetailFicheJourTransfo $detailFicheJourTransfo): static
    {
        if ($this->detailFicheJourTransfos->removeElement($detailFicheJourTransfo)) {
            // set the owning side to null (unless already changed)
            if ($detailFicheJourTransfo->getCodeFiche() === $this) {
                $detailFicheJourTransfo->setCodeFiche(null);
            }
        }

        return $this;
    }
}

src/Controller/Transformation/BillonController.php
<?php

namespace App\Controller\Transformation;

use App\Controller\Services\AdministrationService;
use App\Controller\Services\Utils;
use App\Entity\Administration\DocStatsGen;
use App\Entity\DocStats\Entetes\Documentlje;
use App\Entity\DocStats\Pages\Pagebcbgfh;
use App\Entity\DocStats\Pages\Pagebcbp;
use App\Entity\DocStats\Pages\Pagebrh;
use App\Entity\DocStats\Pages\Pagelje;
use App\Entity\DocStats\Saisie\Lignepagebrh;
use App\Entity\DocStats\Saisie\Lignepagelje;
use App\Entity\References\Essence;
use App\Entity\References\TypeTransformation;
use App\Entity\References\Usine;
use App\Entity\Transformation\Billon;
use App\Entity\Transformation\Elements;
use App\Entity\Transformation\FicheLot;
use App\Entity\Transformation\FicheLotProd;
use App\Entity\User;
use App\Repository\Administration\NotificationRepository;
use App\Repository\DocStats\Pages\PagebrhRepository;
use App\Repository\GroupeRepository;
use App\Repository\MenuPermissionRepository;
use App\Repository\MenuRepository;
use App\Repository\References\PageDocGenRepository;
use App\Repository\Transformation\BillonRepository;
use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;
use PHPUnit\Util\Type;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Contracts\Translation\TranslatorInterface;

class BillonController extends AbstractController
{

    public function __construct(private TranslatorInterface $translator, private Utils $utils, private AdministrationService $administrationService)
    {
    }


    #[Route('/snvlt/trans/billon/gen', name: 'app_trans_ind_billon')]
    public function billon_interface_industriel(ManagerRegistry $registry,
                                                BillonRepository $billonRepository,
                                                Request $request,
                                                MenuPermissionRepository $permissions,
                                                MenuRepository $menus,
                                                GroupeRepository $groupeRepository,
                                                UserRepository $userRepository,
                                                User $user = null,
                                                NotificationRepository $notification): Response
    {
        if(!$request->getSession()->has('user_session')){
            return $this->redirectToRoute('app_login');
        } else {
            if ($this->isGranted('ROLE_INDUSTRIEL') or $this->isGranted('ROLE_MINEF') or $this->isGranted('ROLE_ADMIN') or $this->isGranted('ROLE_ADMINISTRATTIF'))
            {
                $user = $userRepository->find($this->getUser());
                $code_groupe = $user->getCodeGroupe()->getId();

                // $billons = $registry->getRepository(Billon::class)->find($user->);

                //$response = new QrCodeResponse($doctrine->getUniqueDoc());
                return $this->render('transformation/billon/index.html.twig', [
                    //'qr_code_doc' => $response,
                    'billes_non_decoupes'=>$registry->getRepository(Lignepagelje::class)->findAll(),
                    'type_transfo'=>$registry->getRepository(TypeTransformation::class)->findAll(),
                    'billons'=>$registry->getRepository(Billon::class)->findAll(),
                    'liste_menus'=>$menus->findOnlyParent(),
                    "all_menus"=>$menus->findAll(),
                    'menus'=>$permissions->findBy(['code_groupe_id'=>$code_groupe]),
                    'liste_parent'=>$permissions,
                    'mes_notifs'=>$notification->findBy(['to_user'=>$user, 'lu'=>false],[],5,0),
                    'groupe'=>$code_groupe,
                    'essences'=>$registry->getRepository(Essence::class)->findAll()
                ]);
            } else {
                return $this->redirectToRoute('app_no_permission_user_active');
            }
        }
    }

    #[Route('/snvlt/trans/billon/stock', name: 'stock_billon')]
    public function stock_billon(ManagerRegistry $registry,
                                 BillonRepository $billonRepository,
                                 Request $request,
                                 MenuPermissionRepository $permissions,
                                 MenuRepository $menus,
                                 GroupeRepository $groupeRepository,
                                 UserRepository $userRepository,
                                 User $user = null,
                                 NotificationRepository $notification): Response
    {
        if(!$request->getSession()->has('user_session')){
            return $this->redirectToRoute('app_login');
        } else {
            if ($this->isGranted('ROLE_INDUSTRIEL') or $this->isGranted('ROLE_MINEF') or $this->isGranted('ROLE_ADMIN') or $this->isGranted('ROLE_ADMINISTRATTIF'))
            {
                $user = $userRepository->find($this->getUser());
                $code_groupe = $user->getCodeGroupe()->getId();

                return $this->render('transformation/billon/stock.html.twig', [
                    'liste_menus'=>$menus->findOnlyParent(),
                    "all_menus"=>$menus->findAll(),
                    'menus'=>$permissions->findBy(['code_groupe_id'=>$code_groupe]),
                    'liste_parent'=>$permissions,
                    'mes_notifs'=>$notification->findBy(['to_user'=>$user, 'lu'=>false],[],5,0),
                    'groupe'=>$code_groupe
                ]);
            } else {
                return $this->redirectToRoute('app_no_permission_user_active');
            }
        }
    }

    #[Route('/snvlt/trans/allbillon/stock/{date_debut}/{date_fin}', name: 'stock_billon_json')]
    public function stock_billon_json(ManagerRegistry $registry,
                                      BillonRepository $billonRepository,
                                      Request $request,
                                      string $date_debut,
                                      string $date_fin,
                                      MenuPermissionRepository $permissions,
                                      MenuRepository $menus,
                                      GroupeRepository $groupeRepository,
                                      UserRepository $userRepository,
                                      User $user = null,
                                      NotificationRepository $notification): Response
    {
        if(!$request->getSession()->has('user_session')){
            return $this->redirectToRoute('app_login');
        } else {
            if ($this->isGranted('ROLE_INDUSTRIEL') or $this->isGranted('ROLE_MINEF') or $this->isGranted('ROLE_ADMIN') or $this->isGranted('ROLE_ADMINISTRATTIF'))
            {
                $user = $userRepository->find($this->getUser());
                $code_groupe = $user->getCodeGroupe()->getId();

                $billons = array();

                if ($user->getCodeindustriel()){
                    $mes_lje = $registry->getRepository(Documentlje::class)->findBy(['code_usine'=>$user->getCodeindustriel()]);
                    foreach($mes_lje as $lje){
                        $mes_pages = $registry->getRepository(Pagelje::class)->findBy(['code_doclje'=>$lje]);
                        foreach($mes_pages as $page){
                            $mes_billes = $registry->getRepository(Lignepagelje::class)->findBy(['code_pagelje'=>$page]);
                            foreach($mes_billes as $bille){
                                $mes_billons = $registry->getRepository(Billon::class)->findBy(['code_lignepagelje'=>$bille]);


                                foreach($mes_billons as $billon){

                                    $datedebut = \DateTime::createFromFormat('Y-m-d', $date_debut);
                                    $datefin = \DateTime::createFromFormat('Y-m-d', $date_fin);
                                    //dd($datedebut);
                                    if($billon->getDateBillonnage() >= $datedebut && $billon->getDateBillonnage() <= $datefin){
                                        $elts = $registry->getRepository(Elements::class)->findBy(['code_billon'=>$billon]);
                                        $nb_elts = 0;
                                        $vol_elts = 0;
                                        $type_transfo = "-";

                                        if ($billon->getTypeTransformation()){
                                            $type_transfo = $billon->getTypeTransformation()->getLibelle();
                                        }

                                        foreach($elts as $elt){
                                            $nb_elts = $nb_elts + $elt->getNombre();
                                            $vol_elts = $vol_elts + $elt->getVolume();
                                        }
                                        $rendement = 0;
                                        if ($billon->getVolume()){
                                            $rendement = round(($vol_elts / $billon->getVolume()) * 100, 3);
                                        }

                                        $usine_prod = "";
                                        if ($billon->getCodeLignepagelje()->getCodePagelje()->getCodeDoclje()->getCodeUsine()->getSigle()){
                                            $usine_prod = $billon->getCodeLignepagelje()->getCodePagelje()->getCodeDoclje()->getCodeUsine()->getSigle();
                                        } else {

templates/transformation/fiche_production/index.html.twig
{% extends 'template_base.html.twig' %}

{% block Title %}
    {% trans %}SNVLT{% endtrans %} - {% trans %}Fiche Production{% endtrans %}
{% endblock %}

{% block titre_page %}
    <h2 class="text-dark font-weight-bold mb-2">
        <img src="{{ asset('assets/images/webapp/wood.png') }}" height="92" alt="fiche_prod">  {% trans %}Fiche Journalière de Production{% endtrans %}
    </h2>
{% endblock %}

 {% block notifs %}
     {% include 'base/notifs.html.twig' %}
 {% endblock %}

 {% block menu %}
     {% include 'base/menu.html.twig' %}
 {% endblock %}

{% block page_content %}


    {#<link rel="stylesheet" href="{{ asset('assets/webapp/assets/vendors/simple-datatables/style.css') }}">#}
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/3.0.1/css/buttons.dataTables.css">
    <link rel="stylesheet" href="{{ asset('assets/assets/css/modal.css') }}" />

    <section class="section">
        <div class="card">
            <h4 class="alert-info p-1 mb-2">Cliquez sur une date de production pour afficher les billons</h4>
            <div class="row p-2">
                <div class="col-md-2 p-2 m-2 " style="height: 550px; border: 1px solid lightgrey">
                    <table class="table table-responsive w-100" style="font-size: 18px;">
                        <thead class="alert-light">
                        <tr>
                            <th class="font-weight-bold w-100" style="font-size: 18px;">Date Tronçonnage</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for fiche in fiches %}
                            <tr>
                                <td class="font-weight-bold" style="font-size: 18px;"><a class="date_prod" href="#" id="{{ fiche.id }}">{{ fiche.dateFiche | date('d/m/Y') }}</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-md-9 m-2 p-2" style="height: 550px; border: 1px solid lightgrey;background-color: #e2e8ec">
                    <div class="card-body text-center  alert-info" id="body_contenu" style="height: 500px;overflow-y: scroll;background-color: #e2e8ec"><img class="img-responsive img-fluid mx-auto my-auto" src="{{ asset('assets/images/logo_snvlt.png') }}" alt="logo_SNVLT" style="height: 256px;"></div>
                </div>
            </div>


        </div>

        <!-- Modal Type Transfo-->
        <div class="modal fade" id="edit_transfo" data-bs-backdrop="static" tabindex="-1">
            <div class="modal-dialog">
                <form class="modal-content">
                    <div class="modal-header alert-success">
                        <h5 class="modal-title" id="backDropModalTitle"><img src="{{ asset('assets/images/webapp/wood.png') }}" alt="daily_sheet" style="margin-right: 10px; height: 32px;">Type transformation</h5>
                        <button
                                type="button"
                                class="btn-close"
                                data-bs-dismiss="modal"
                                aria-label="Close"
                        ></button>
                    </div>
                    <div class="modal-body">

                        <select class="form-control alert-warning" style="font-size: 18px;" name="id_transfo" id="id_transfo">
                            <option value="0">Sélectionner le type de transformation</option>
                            {% for transfo in app.user.codeindustriel.typeTransformation %}
                                <option value="{{ transfo.id }}">{{ transfo.libelle }}</option> +
                            {% endfor %}
                        </select>
                        <div class="text-center mt-3">

                            <a type="button" class="btn btn-primary font-weight-light  accept_loading" id="valider_transfo" style="font-size: 16px;margin-left: 15px;">
                                <i class="mdi mdi-check-circle text-white ms-4" style="font-size: 20px;margin-right: 5px;"></i> Sélectionner
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>

    <script src="https://cdn.datatables.net/buttons/3.0.1/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.1/js/buttons.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src=" https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.1/js/buttons.print.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script>

        let id_billon = 0;

        $('.date_prod').on('click', function(){
            affiche_billons(this.id)
        })
        function affiche_billons(id_fiche){

            let contenu = "";
            $.ajax({
                url : '{{ path('app_portail') }}snvlt/prod/ficheProd/' + id_fiche,
                type: 'POST',
                success : function (response){
                    let valeur = JSON.parse(response);
                    if (valeur.length > 0){
                        contenu = '<a class="btn p-1 mb-2 text-white btn_imprimer" href="{{ path('app_portail') }}snvlt/PrintFicheProd/' + id_fiche + '" target="_blank" style="background: orangered;font-size:18px;" id="' + id_fiche + '"><i class="mdi mdi-printer me-2"></i> Imprimer la fiche</a>'
                        contenu = contenu +'<div class=" mx-auto text-center"><table class="table" style="border: #0a0a0a solid 1px;">' +
                            '<thead class="font-weight-bold alert-light mx-auto">' +
                            '<th>Essence</th>' +
                            '<th>Lng</th>' +
                            '<th>Lrg</th>' +
                            '<th>Ep</th>' +
                            '<th>Nbre Elts</th>' +
                            '<th>Volume</th>' +
                            '<th>Transformation</th>' +
                            '<th>Billons</th>' +
                            '</thead>' +
                            '<tbody class=" mx-auto">';
                        if (valeur.length > 0){
                            for(var i=0;i<valeur.length;i++){
                                contenu = contenu + '<tr class="bg-white">';
                                contenu = contenu + '<td class="font-weight-bold" style="font-size: 18px;">' + valeur[i].essence + '</td>';
                                contenu = contenu + '<td class="" style="font-size: 18px;">' + valeur[i].lng + '</td>';
                                contenu = contenu + '<td class="" style="font-size: 18px;">' + valeur[i].lrg + '</td>';
                                contenu = contenu + '<td class="" style="font-size: 18px;">' + valeur[i].ep + '</td>';
                                contenu = contenu + '<td class="" style="font-size: 18px;">' + valeur[i].nb + '</td>';
                                contenu = contenu + '<td class="" style="font-size: 18px;">' + valeur[i].vol + '</td>';
                                contenu = contenu + '<td class="" style="font-size: 18px;">' + valeur[i].type_transfo + '</td>';
                                contenu = contenu + '<td class="text-left" style="font-size: 18px;">';
                                if (valeur[i].type_transfo === "DEROULAGE"){
                                    let billons = ";"
                                    for(var j=0;j<valeur[i].billons.length;j++){
                                        billons = billons + '<span class="badge bg-dark text-white font-weight-bold me-2" style="font-size: 18px;">' + valeur[i].billons[j].numero_billon + '</span>'+ " ";
                                    }
                                        contenu = contenu + billons
                                } else {
                                    contenu = contenu + '<span class="font-weight-bold me-2">' + valeur[i].billons
                                }

                                contenu = contenu + '</td>';
                                contenu = contenu + '</tr>';
                            }
                            contenu = contenu + '</tbody></table></div>'
                        }
                        document.querySelector('#body_contenu').innerHTML = contenu;

                    }
                }
            })
        }

        $('body').on('click', '.btn_imprimer', function (){
            let id_fiche = this.id;
            $.ajax({
                url: '{{ path('app_portail') }}snvlt/PrintPdf/FicheProd/' + id_fiche,
                type: 'POST',
                success: function (response) {
                    let reponse = JSON.parse(response);
                }
            });

        });

        $('body').on('change', '.select_transfo', function (){
            let id_billon = this.id;
            let id_type_transfo = this.value;
            $.ajax({
                url: '{{ path('app_portail') }}snvlt/liste_billons/fiche_lot/billon/maj_transfo/' + id_billon + '/' + id_type_transfo,
                type: 'POST',
                success: function (response) {
                    let reponse = JSON.parse(response);
                    if (reponse[0].code === "SUCCESS"){
                        let date_tronconnage = $('#date_tronconnage').val();
                        affiche_billons(date_tronconnage)
                        alert('Transformation mise à jour');
                    }
                }
            });

        })
        $('body').on('click', '.edit_transfo', function (){
            id_billon = this.id;
        })
        $('body').on('click', '#valider_transfo', function (){
            let id_type_transfo = $('#id_transfo').val();
            $.ajax({
                url: '{{ path('app_portail') }}snvlt/liste_billons/fiche_lot/billon/maj_transfo/' + id_billon + '/' + id_type_transfo,
                type: 'POST',
                success: function (response) {
                    let reponse = JSON.parse(response);
                    if (reponse[0].code === "SUCCESS"){
                        let date_tronconnage = $('#date_tronconnage').val();
                        affiche_billons(date_tronconnage)
                        $('#edit_transfo').modal('hide')
                    }
                }
            });

        })
    </script>



{% endblock %}