src/Entity/Administration/DemandeOperateur.php
<?php

namespace App\Entity\Administration;

use App\Entity\Autorisation\AutorisationPs;
use App\Entity\Autorisation\AutorisationPv;
use App\Entity\Autorisation\Reprise;
use App\Entity\DocStats\Entetes\Documentbcbp;
use App\Entity\DocStats\Entetes\Documentbrepf;
use App\Entity\DocStats\Entetes\Documentbrh;
use App\Entity\DocStats\Entetes\Documentbtgu;
use App\Entity\DocStats\Entetes\Documentbth;
use App\Entity\DocStats\Entetes\Documentcp;
use App\Entity\DocStats\Entetes\Documentdmp;
use App\Entity\DocStats\Entetes\Documentdmv;
use App\Entity\DocStats\Entetes\Documentetate;
use App\Entity\DocStats\Entetes\Documentetate2;
use App\Entity\DocStats\Entetes\Documentetatg;
use App\Entity\DocStats\Entetes\Documentetath;
use App\Entity\DocStats\Entetes\Documentfp;
use App\Entity\DocStats\Entetes\Documentlje;
use App\Entity\DocStats\Entetes\Documentpdtdrv;
use App\Entity\DocStats\Entetes\Documentrsdpf;
use App\Entity\References\CircuitCommunication;
use App\Entity\References\Commercant;
use App\Entity\References\Exportateur;
use App\Entity\References\TypeDocumentStatistique;
use App\Entity\References\TypeOperateur;
use App\Entity\References\Usine;
use App\Entity\User;
use App\Repository\DemandeOperateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
#[ORM\Table(name: 'metier.demande_operateur')]
#[ORM\Entity(repositoryClass: DemandeOperateurRepository::class)]
class DemandeOperateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'demandeOperateurs')]
    private ?TypeDocumentStatistique $doc_stat = null;

    #[ORM\Column(nullable: true)]
    private ?int $qte = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $created_by = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $updated_by = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $statut = null;

    #[ORM\Column(nullable: true)]
    private ?bool $transmission = null;

    #[ORM\Column(nullable: true)]
    private ?bool $verification = null;

    #[ORM\Column(nullable: true)]
    private ?bool $delivrance = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_verification = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_delivrance = null;

    #[ORM\ManyToOne(inversedBy: 'demandeOperateurs')]
    private ?User $demandeur = null;

    #[ORM\Column(nullable: true)]
    private ?int $qte_validee = null;

    #[ORM\Column(nullable: true)]
    private ?int $qte_delivree = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $motif_verification = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $motif_delivrance = null;

    #[ORM\ManyToOne(inversedBy: 'demandeOperateurs')]
    private ?TypeOperateur $code_operateur = null;

    #[ORM\Column(nullable: true)]
    private ?int $code_structure = null;

    #[ORM\ManyToOne(inversedBy: 'demandeOperateurs')]
    private ?Reprise $code_reprise = null;

    #[ORM\OneToMany(mappedBy: 'code_demande_operateur', targetEntity: CircuitCommunication::class)]
    private Collection $circuitCommunications;

    #[ORM\Column(nullable: true)]
    private ?bool $docs_generes = null;

    #[ORM\ManyToOne(inversedBy: 'demandeOperateurs')]
    private ?Usine $code_usine = null;

    #[ORM\ManyToOne(inversedBy: 'demandeOperateurs')]
    private ?Exportateur $code_exportateur = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $code = null;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentbrh::class)]
    private Collection $documentbrhs;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentcp::class)]
    private Collection $documentcps;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentlje::class)]
    private Collection $documentljes;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentbtgu::class)]
    private Collection $documentbtgus;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentfp::class)]
    private Collection $documentfps;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentbcbp::class)]
    private Collection $documentbcbps;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentetate::class)]
    private Collection $documentetates;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentetate2::class)]
    private Collection $documentetate2s;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentetatg::class)]
    private Collection $documentetatgs;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentetath::class)]
    private Collection $documentetaths;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentdmp::class)]
    private Collection $documentdmps;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentdmv::class)]
    private Collection $documentdmvs;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentpdtdrv::class)]
    private Collection $documentpdtdrvs;

    #[ORM\ManyToOne(inversedBy: 'demandeOperateurs')]
    private ?AutorisationPv $code_autorisation_pv = null;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentbrepf::class)]
    private Collection $documentbrepfs;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentrsdpf::class)]
    private Collection $documentrsdpfs;

    #[ORM\OneToMany(mappedBy: 'code_demande', targetEntity: Documentbth::class)]
    private Collection $documentbths;

    #[ORM\ManyToOne(inversedBy: 'demandeOperateurs')]
    private ?AutorisationPs $code_autorisationps = null;

    #[ORM\ManyToOne(inversedBy: 'demandeOperateurs')]
    private ?Commercant $code_commercant = null;

    #[ORM\Column(nullable: true)]
    private ?bool $signature_dr = null;

    #[ORM\Column(nullable: true)]
    private ?bool $signature_cef = null;

    public function __construct()
    {
        $this->circuitCommunications = new ArrayCollection();
        $this->documentbrhs = new ArrayCollection();
        $this->documentcps = new ArrayCollection();
        $this->documentljes = new ArrayCollection();
        $this->documentbtgus = new ArrayCollection();
        $this->documentfps = new ArrayCollection();
        $this->documentbcbps = new ArrayCollection();
        $this->documentetates = new ArrayCollection();
        $this->documentetate2s = new ArrayCollection();
        $this->documentetatgs = new ArrayCollection();
        $this->documentetaths = new ArrayCollection();
        $this->documentdmps = new ArrayCollection();
        $this->documentdmvs = new ArrayCollection();
        $this->documentpdtdrvs = new ArrayCollection();
        $this->documentbrepfs = new ArrayCollection();
        $this->documentrsdpfs = new ArrayCollection();
        $this->documentbths = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDocStat(): ?TypeDocumentStatistique
    {
        return $this->doc_stat;
    }

    public function setDocStat(?TypeDocumentStatistique $doc_stat): static
    {
        $this->doc_stat = $doc_stat;

        return $this;
    }

    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(?int $qte): static
    {
        $this->qte = $qte;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(?string $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUpdatedBy(): ?string
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(string $updated_by): static
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function isTransmission(): ?bool
    {
        return $this->transmission;
    }

    public function setTransmission(?bool $transmission): static
    {
        $this->transmission = $transmission;

        return $this;
    }

    public function isVerification(): ?bool
    {
        return $this->verification;
    }

    public function setVerification(?bool $verification): static
    {
        $this->verification = $verification;

        return $this;
    }

    public function isDelivrance(): ?bool
    {
        return $this->delivrance;
    }

    public function setDelivrance(?bool $delivrance): static
    {
        $this->delivrance = $delivrance;

        return $this;
    }

    public function getDateVerification(): ?\DateTimeInterface
    {
        return $this->date_verification;
    }

    public function setDateVerification(?\DateTimeInterface $date_verification): static
    {

src/Entity/Administration/FicheProspection.php
<?php

namespace App\Entity\Administration;

use App\Entity\Autorisation\Attribution;
use App\Entity\References\Exploitant;
use App\Repository\Administration\FicheProspectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
#[ORM\Table(name: 'metier.fiche_prospection')]
#[ORM\Entity(repositoryClass: FicheProspectionRepository::class)]
class FicheProspection
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fichier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $created_by = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'ficheProspections')]
    private ?Attribution $code_attribution = null;

    #[ORM\OneToMany(mappedBy: 'code_fiche_prospection', targetEntity: InventaireForestier::class)]
    private Collection $inventaireForestiers;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $updated_by = null;

    #[ORM\OneToMany(mappedBy: 'code_fichep', targetEntity: ProspectionTemp::class)]
    private Collection $prospectionTemps;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lien_complet = null;

    #[ORM\ManyToOne(inversedBy: 'ficheProspections')]
    private ?Exploitant $code_exploitant = null;

    #[ORM\Column(nullable: true)]
    private ?bool $valide = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_inventaire = null;

    public function __construct()
    {
        $this->inventaireForestiers = new ArrayCollection();
        $this->prospectionTemps = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFichier(): ?string
    {
        return $this->fichier;
    }

    public function setFichier(string $fichier): static
    {
        $this->fichier = $fichier;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(string $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCodeAttribution(): ?Attribution
    {
        return $this->code_attribution;
    }

    public function setCodeAttribution(?Attribution $code_attribution): static
    {
        $this->code_attribution = $code_attribution;

        return $this;
    }

    /**
     * @return Collection<int, InventaireForestier>
     */
    public function getInventaireForestiers(): Collection
    {
        return $this->inventaireForestiers;
    }

    public function addInventaireForestier(InventaireForestier $inventaireForestier): static
    {
        if (!$this->inventaireForestiers->contains($inventaireForestier)) {
            $this->inventaireForestiers->add($inventaireForestier);
            $inventaireForestier->setCodeFicheProspection($this);
        }

        return $this;
    }

    public function removeInventaireForestier(InventaireForestier $inventaireForestier): static
    {
        if ($this->inventaireForestiers->removeElement($inventaireForestier)) {
            // set the owning side to null (unless already changed)
            if ($inventaireForestier->getCodeFicheProspection() === $this) {
                $inventaireForestier->setCodeFicheProspection(null);
            }
        }

        return $this;
    }

    public function getUpdatedBy(): ?string
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?string $updated_by): static
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * @return Collection<int, ProspectionTemp>
     */
    public function getProspectionTemps(): Collection
    {
        return $this->prospectionTemps;
    }

    public function addProspectionTemp(ProspectionTemp $prospectionTemp): static
    {
        if (!$this->prospectionTemps->contains($prospectionTemp)) {
            $this->prospectionTemps->add($prospectionTemp);
            $prospectionTemp->setCodeFichep($this);
        }

        return $this;
    }

    public function removeProspectionTemp(ProspectionTemp $prospectionTemp): static
    {
        if ($this->prospectionTemps->removeElement($prospectionTemp)) {
            // set the owning side to null (unless already changed)
            if ($prospectionTemp->getCodeFichep() === $this) {
                $prospectionTemp->setCodeFichep(null);
            }
        }

        return $this;
    }

    public function getLienComplet(): ?string
    {
        return $this->lien_complet;
    }

    public function setLienComplet(?string $lien_complet): static
    {
        $this->lien_complet = $lien_complet;

        return $this;
    }

    public function getCodeExploitant(): ?Exploitant
    {
        return $this->code_exploitant;
    }

    public function setCodeExploitant(?Exploitant $code_exploitant): static
    {
        $this->code_exploitant = $code_exploitant;

        return $this;
    }

    public function isValide(): ?bool
    {
        return $this->valide;
    }

    public function setValide(?bool $valide): static
    {
        $this->valide = $valide;

        return $this;
    }

    public function getDateInventaire(): ?\DateTimeInterface
    {
        return $this->date_inventaire;
    }

    public function setDateInventaire(?\DateTimeInterface $date_inventaire): static
    {
        $this->date_inventaire = $date_inventaire;

        return $this;
    }
}

src/Entity/Administration/PieceJointe.php
<?php

namespace App\Entity\Administration;

use App\Repository\Administration\PieceJointeRepository;
use Doctrine\ORM\Mapping as ORM;
#[ORM\Table(name: 'metier.piece_jointe')]
#[ORM\Entity(repositoryClass: PieceJointeRepository::class)]
class PieceJointe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fichier = null;

    #[ORM\ManyToOne(inversedBy: 'pieceJointes')]
    private ?Messagerie $code_email = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFichier(): ?string
    {
        return $this->fichier;
    }

    public function setFichier(?string $fichier): static
    {
        $this->fichier = $fichier;

        return $this;
    }

    public function getCodeEmail(): ?Messagerie
    {
        return $this->code_email;
    }

    public function setCodeEmail(?Messagerie $code_email): static
    {
        $this->code_email = $code_email;

        return $this;
    }
}

templates/administration/inventaire_forestier/fiche_print.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ asset('assets/bootstrap-5.3.2/dist/css/bootstrap.min.css') }}">
    <title>Fiche LAAC N° {{ fiche.id }}</title>
</head>
<body id="inv_body">
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
    th{
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        background-color: #135402;
        color:white;
    }

    tr:nth-child(odd) {
        background-color: #dddddd;
    }

</style>

<div class="" id="table_inv"  style="margin: 10px 10px 10px 10px;padding: 10px;">

                    <div class="row" style="background-color:#e4f4d1 ">
                        <img class="col-md-2" src="{{ asset('assets/images/logo_snvlt.png') }}" alt="">
                        <h2 class="col-md-10 my-auto p-2" style="border-radius: 10px 10px 10px 10px">Système National de légalité et de traçabilité du bois</h2>
                    </div>
                    <hr>
                    <div class="bg-light p-2" style="background-color:#f2f2ff "><span style="background-color: #cfd5d4">Exploitant</span> : <span class="fw-bold text-primary">{{ fiche.codeAttribution.codeExploitant.sigle }}</span></div>
                    <div class="bg-light p-2" style="background-color:#f2f2ff "><span style="background-color: #cfd5d4">Forêt </span> : <span class="fw-bold">{{ fiche.codeAttribution.codeForet.denomination }}</span></div>
                    <div class="bg-light p-2" style="background-color:#f2f2ff "><span style="background-color: #cfd5d4">N° Fiche LAAC</span> : <span class="fw-bold">{{ fiche.id }}</span></div>
                    <div class="bg-light p-2" style="background-color:#f2f2ff "><span style="background-color: #cfd5d4">imprimé le </span> : <label class="fw-bold" id="date_sys"></label></div>
                    <hr>
                    <div class="text-center">
                        <h3  style="font-weight: bold;">Liste définitive des Arbres à Couper (LAAC)</h3>
                    <br>

                    <table id="table_lac_details">
                        <thead style="background: lightgrey;">
                        <tr class="alert-success">
                            <th style="font-size: 20px;">Essence</th>
                            <th class="text-center" style="font-size: 20px;">N° Arbre Inv</th>
                            <th class="text-center" style="font-size: 20px;">Zone</th>
                            <th class="text-center" style="font-size: 20px;">X</th>
                            <th class="text-center" style="font-size: 20px;">Y</th>
                            <th style="font-size: 20px;">Longueur</th>
                            <th style="font-size: 20px;">Diamètre</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for arbre in fiche.inventaireForestiers %}
                            {% if (arbre.lac) %}
                                <tr class="p-1" style="font-size: 18px;">
                                {% if not (arbre.valide) %}
                                    <tr class="p-1 alert-danger" style="font-size: 18px;">
                                {% endif %}

                                <td>{{ arbre.codeEssence.nomVernaculaire }}</td>
                                <td class="text-center">{{ arbre.numeroArbre }}</td>
                                <td class="text-center">{{ arbre.zoneh.zone }}</td>
                                <td class="text-center">{{ arbre.x }}</td>
                                <td class="text-center">{{ arbre.y }}</td>
                                <td>{{ arbre.lng }}</td>
                                <td>{{ arbre.dm }}</td>
                                </tr>
                            {% else %}

                            {% endif %}



                        {% endfor %}
                        </tbody>
                    </table>
                    </div>

</div>
<script src=
        "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
</script>
<script src=
        "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js">
</script>
<script src=
        "https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js">
</script>
<script>
    const { jsPDF } = window.jspdf;

    let doc = new jsPDF('portrait', 'mm', [1600,2263]);
    let pdfjs = document.querySelector('#inv_body');
    var fullDate = new Date();

    var d = new Date();

    var month = d.getMonth()+1;
    var day = d.getDate();

    var output = (day<10 ? '0' : '') + day  + '/' +
            (month<10 ? '0' : '') + month + '/' +
            d.getFullYear() ;

    $("#date_sys").text(output)

    $(document).ready(function () {

        convertHTMLtoPDF();



        function convertHTMLtoPDF() {



            doc.html(pdfjs, {
                callback: function(doc) {
                    doc.save("{{ fiche.codeAttribution.codeForet.denomination }}-{{ fiche.id }}.pdf");
                },
                margin: [35, 35, 50, 35]
            });
            closeWin();
            //getPages()
        }
    });

    function getPages(){
        var pageCount = doc.internal.getNumberOfPages(); //Total Page Number
        //alert(pageCount)
        for(i = 1; i < pageCount + 1; i++) {
            doc.setPage(i);
            let pageCurrent = doc.internal.getCurrentPageInfo().pageNumber; //Current Page
            doc.setFontSize(20);
            doc.text('page: ' + pageCurrent + '/' + pageCount, 10, doc.internal.pageSize.height - 10);
        }

    }
    function closeWin() {

    }
</script>
</body>
</html>

templates/administration/inventaire_forestier/validation_lac.html.twig
{% extends 'template_base.html.twig' %}

{% block Title %}
    {% trans %}SNVLT{% endtrans %} - {% trans %}Validation LAAC{% endtrans %}
{% endblock %}

{% block titre_page %}
    <h2 class="text-dark font-weight-bold mb-2">
        <img src="{{ asset('assets/images/webapp/valid.png') }}" alt="forest">  {% trans %}Validation LAAC{% endtrans %}
    </h2>
    <div class="mb-2 mt-2">
        <span id="lbl_exploitant" class="h5 text-danger font-weight-bold"></span>
        <select name="parc_usine" id="foret" data-placeholder="foret" style="font-size: 16px;background-color: #fcf378; border: 1px solid lightgrey;">
            {#{% for usine in usines %}
            <option value="{{ usine.id }}">{{ usine.sigle }}</option>
        {% endfor %}#}
        </select>

    </div>
{% endblock %}

 {% block notifs %}
     {% include 'base/notifs.html.twig' %}
 {% endblock %}

 {% block menu %}
     {% include 'base/menu.html.twig' %}
 {% endblock %}

{% block page_content %}

    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.4/css/dataTables.dataTables.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/3.1.1/css/buttons.dataTables.css" />
    <script src="https://cdn.datatables.net/2.1.4/js/dataTables.js"></script>
    <link rel="stylesheet" href="{{ asset('assets/assets_other/vendor/fonts/boxicons.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/assets/css/modal.css') }}" />

    <!-- Latest compiled and minified CSS -->

    <section class="section bg-white p-1">
        <div class="p-2" style="border: orange; min-height: 500px;" id="liste_arbres">
            <table class="table" id="table_inventaire" style="border:1px solid lightgrey">
                <thead class="text-white bg-dark font-weight-bold">
                    <th class="text-center">Forêt</th>
                    <th class="text-center">N° Fiche</th>
                    <th>Exploitant</th>
                    <th>Cantonnement</th>
                    <th class="text-center">Date Chargement</th>
                    <th class="text-center">Status</th>
                </thead>
                <tbody>
                {% for fiche in liste_fiches %}
                    {% if not (fiche.valide) %}
                        <tr class="font-weight-bold text-danger" style="border-bottom: 1px solid lightgrey;font-size: 18px;">
                    {% else %}
                        <tr class="alert-success" style="border-bottom: 1px solid lightgrey;font-size: 18px;">
                    {% endif%}
                        <td class="text-center"><a style="font-size: 18px;background: #0f3a0f;" class="btn p-1 text-white" href="{{ path('app_valid_fiche_lac_idfiche', {'id_fiche': fiche.id}) }}">{{ fiche.codeAttribution.codeForet.denomination }}</td>
                        <td class="font-weight-bold text-dark text-center">{{ fiche.id }}</td>

                        {% if (fiche.codeAttribution.codeExploitant) %}
                            <td>{{ fiche.codeAttribution.codeExploitant.sigle }}</td>
                        {% else %}
                            <td>-</td>
                        {% endif %}

                        {% if(fiche.codeAttribution.codeForet.codeCantonnement) %}
                            <td>{{ fiche.codeAttribution.codeForet.codeCantonnement.nomCantonnement }}</td>
                        {% else %}
                            <td>-</td>
                        {% endif %}

                        <td class="text-center">{{ fiche.createdAt | date('d/m/Y') }}</td>
                        <td class="text-center">
                            {% if (fiche.valide) %}
                                <img src="{{ asset('assets/icons/checkmark.png') }}" alt="valide">
                            {% else %}
                                <i class="mdi mdi-stop-circle text-danger" style="font-size: 24px;"></i>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>


    <script src="{{ asset('assets/webapp/assets/vendors/jquery/jquery.min.js') }}"></script>

    <script src="https://cdn.datatables.net/2.1.4/js/dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://cdn.datatables.net/buttons/3.1.1/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.1/js/buttons.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.1/js/buttons.print.min.js"></script>
    <script src="{{ asset('assets/Js/utilitaires.js') }}"></script>

    <script>
        dataTableSnvlt("#table_inventaire", "Fiches LAAC", 20)
    </script>
{% endblock %}